// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgISf3VkDQ_ajuyUEwBi7e_3xd1XxuWu0',
    appId: '1:524848303801:web:2bce4031b586d71cf01568',
    messagingSenderId: '524848303801',
    projectId: 'the-elsewheres',
    authDomain: 'the-elsewheres.firebaseapp.com',
    storageBucket: 'the-elsewheres.firebasestorage.app',
    measurementId: 'G-X1SYHK3MZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlsKy4_CL84AuzGON5ucpOLE9Eo1ac-c',
    appId: '1:524848303801:android:8a24621a9ebf74bef01568',
    messagingSenderId: '524848303801',
    projectId: 'the-elsewheres',
    storageBucket: 'the-elsewheres.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5hC0yUDw-QDYnr5Z3zcJr1EqvUzboxo',
    appId: '1:524848303801:ios:2623530201db8e33f01568',
    messagingSenderId: '524848303801',
    projectId: 'the-elsewheres',
    storageBucket: 'the-elsewheres.firebasestorage.app',
    iosBundleId: 'com.example.theElsewheres',
  );
}
